site_name: floquet
site_description: Documentation for the floquet software library
site_author: Daniel Weiss
site_url: http://dkweiss.net/floquet/

repo_url: https://github.com/dkweiss31/floquet
repo_name: dkweiss31/floquet
edit_uri: ""

theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
    palette:
        - scheme: default
          primary: indigo
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right

extra_javascript:
    # To make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: false
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    members_order: source
                    heading_level: 4
                    inherited_members: true  # Allow looking up inherited methods

nav:
    - 'index.md'
    - API:
        - 'floquet.md'
    - FAQ:
        - 'FAQ.md'
    - Examples:
        - Transmon: 'examples/transmon.ipynb'
        - Qubit parameter sweep: 'examples/EJ_sweep.ipynb'
        - Parametric driving: 'examples/parametric.ipynb'
        - Fluxonium: 'examples/fluxonium.ipynb'
